### ISSUE TITLE
printfs are all screwy for some builds

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#28]
```
RUNTIME>x l
Video sources:
input0 (0): <NULL>

input1 (1): <NULL>

pattern (p):
  Video pattern

Video sinks:
output0 (0): <NULL>

output1 (1): <NULL>

encoder (e):
  JPEG encoder (USB output)

RUNTIME>x c 0 1
Connecting <NULL> to output1073798624
RUNTIME>x c p 1
Connecting <NULL> to output1073798624
RUNTIME>x c 0 p
```

Probably related to https://github.com/enjoy-digital/opsis-soc/issues/26

**Comment by enjoy-digital** [comment]
Using `opsis_base` target on a real Opsis board.

```
RUNTIME>status
ddr: read:1073778324Mbps  write:  105Mbps  all:268435704Mbps
```

**Comment by mithro** [comment]
The problem causing this `ci_printf` function at https://github.com/enjoy-digital/opsis-soc/blob/master/firmware/ci.c#L37

You can't pass variable args forward like this. The compiler sees that the variable args are not used and thus optimises them out.

The two options to fix this are;

 * Use va_args properly. This can be found in branch -> https://github.com/enjoy-digital/opsis-soc/compare/hdmi2usb...mithro:printf-fix-1
   The problem with this approach are;
    - The output can only be sent to *one* va_args function. You can't send the output to both Ethernet and console.
    - libbase is currently missing vprintf (Fixed in https://github.com/enjoy-digital/litex/pull/9)

 * Use a macro rather than a function.  This can be found in branch -> https://github.com/enjoy-digital/opsis-soc/compare/hdmi2usb...mithro:printf-fix-2
   The problem with this approach are;
    - If the printf does something weird in the arguments (like a++) it will get incremented twice.
   - Macros like this are a pain.
