### ISSUE TITLE
LiteEth not working in larger designs

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#34]
Split out of https://github.com/enjoy-digital/opsis-soc/issues/1

Once https://github.com/enjoy-digital/opsis-soc/pull/32 is merged, liteEth again works correctly on the MiniSoC target.

It however still fails on the `opsis_video` and `opsis_hdmi2usb` targets. It is likely related to the checksum problems at https://github.com/enjoy-digital/opsis-soc/issues/30

**Comment by enjoy-digital** [comment]
Fixed via https://github.com/enjoy-digital/opsis-soc/commit/4aee8f102d668967f859d26052c1963c0295e643.

**Comment by mithro** [comment]
Did you see this?
```
WARNING:PhysDesignRules:1441 - Issue with pin connections and/or configuration
   on block:<rgmii_if/rgmii_rx_ctl_in>:<ILOGIC2_IFF>.  The IFFTYPE is DDR and
   the Q2 output pin of IFF is not used.
```

**Comment by enjoy-digital** [comment]
gmii_rx_er_reg not used --> rgmii_rx_ctl_reg removed --> Q1 open.
We can ignore that.

**Comment by mithro** [comment]
With your changes, I can tftp boot the opsis_video target. The telnet interface worked for a little bit and then became unreliable.

On my machine, the ethernet adapter says;
```
sudo mii-tool usb0                                                                                                                     
usb0: negotiated 1000baseT-FD flow-control, link ok
```

But the device says;
```
RUNTIME>mdio_status
MDIO mode: 10Mbps / link: up
RUNTIME>mdio_dump
reg 0: 4000d70c
reg 0: 4000d70c
reg 0: 4000d70c
reg 0: 4000d70c
```

Going to compare to opsis_base now

**Comment by enjoy-digital** [comment]
Closing, others issues are open for unrelated problems:
https://github.com/enjoy-digital/opsis-soc/issues/36
https://github.com/enjoy-digital/opsis-soc/issues/37
