### ISSUE TITLE
mdio_status reports wrong speed

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#36]
On my machine, the ethernet adapter says;

```
sudo mii-tool usb0
usb0: negotiated 1000baseT-FD flow-control, link ok
```

But the device says:

```
RUNTIME>mdio_status
MDIO mode: 10Mbps / link: up
```

**Comment by enjoy-digital** [comment]
Fixed via https://github.com/enjoy-digital/opsis-soc/commit/a28c3846411879e765b7875c88e4ffddda21a19f.

**Comment by mithro** [comment]
mdio_status is still seems to be broken on the opsis_hdmi2usb soc.
```
RUNTIME>mdio_status
MDIO mode: Reserved / link: up
RUNTIME>mdio_dump
reg 0: ffff
reg 1: ffff
reg 2: ffff
reg 3: ffff
```

Checking if this is the case with opsis_minisoc too.

**Comment by mithro** [comment]
opsis_minisoc seems to work fine;
```
RUNTIME>mdio_status
MDIO mode: 1000Mbps / link: up
RUNTIME>mdio_dump
reg 0: 1140
reg 1: 7969
reg 2: 001c
reg 3: c915
reg 4: 05e1
reg 5: cde1
reg 6: 000d
reg 7: 2001
reg 8: 6801
reg 9: 0200
reg 10: 4800
reg 11: 0000
reg 12: 0000
reg 13: 0000
reg 14: 0000
reg 15: 3000
reg 16: 016e
reg 17: ac82
reg 18: 9f01
reg 19: 6c52
reg 20: 8040
reg 21: 1006
reg 22: 4100
reg 23: 2100
reg 24: 0000
reg 25: 8c00
reg 26: 0040
reg 27: 0102
reg 28: 41cc
reg 29: 8038
reg 30: 0123
reg 31: 0000
RUNTIME>
```

**Comment by mithro** [comment]
I've double checked now, `mdio_status` definitely works on `opsis_minisoc` but fails on `opsis_hdmi2usb`  (by just reading `ffff` in all the registers) checking `opsis_video`.

**Comment by mithro** [comment]
`opsis_video` correctly works.

**Comment by enjoy-digital** [comment]
thanks for reporting, I'll check that while I'll be tetsting hdmi2usb.

**Comment by mithro** [comment]
It seems to work now...
