### ISSUE TITLE
Get SoC working on other platforms

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#5]
The other platforms we currently have are;
- [ ] Atlys
- [ ] Pippisterello
- [ ] Minispartan6+

**Comment by enjoy-digital** [comment]
We'll do that once opsis-soc will be merged in HDMI2USB. Let's concentrate on the Opsis board here.

**Comment by mithro** [comment]
To merge into HDMI2USB firmware branch, we need atleast the Atlys board working too.

**Comment by mithro** [comment]
@shenki is currently working on the minispartan6+ stuff.

**Comment by enjoy-digital** [comment]
OK to do this in the hdmi2usb branch. We'll remove this branch when merge in HDMI2USB repo.

**Comment by mithro** [comment]
Platforms are imported at https://github.com/mithro/HDMI2USB-litex-firmware/tree/nextgen/targets

Current status:
 * opsis seems to be mostly working
 * mimasv2 worked before trying to move to boot from SPI flash
 * atlys BaseSoC seems to work, NetSoC doesn't compile
 * minispartan6 still has broken SDRAM
 * No work on pipistrello

**Comment by mithro** [comment]
Current status:
 * opsis works
 * mimasv2 works
 * atlys seems to work

 * minispartan6 still has broken SDRAM.
 * No testing on pipistrello.

 * Some NeTV2 and nexys_video bits work.

I think we can close this for now.
