### ISSUE TITLE
Figure out `firmware/uip`

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#7]
What is it used for?
Where does it come from?

It actually looks like libuip is the custom code for this SoC and uip is the library, this feels backwards?

The code should probably be a submodule. 
It should also be in `third_party` directory.

**Comment by enjoy-digital** [comment]
It's the TCP/UDP/IP stack from contiki (http://www.contiki-os.org/).
We are using it for telnet, etherbone, ... and could probably move this to LiteEth.

**Comment by mithro** [comment]
Pull request at https://github.com/enjoy-digital/opsis-soc/pull/20 is a require for doing this.

**Comment by mithro** [comment]
So there are two directories;
 * `firmware/libuip` - Contains the functions required by the uip stack to control liteeth
 * `firmware/uip` - Contains the TCP/UDP/IP stack from contiki.

Still need to figure out what "version of contiki" the sources come from -- the `contiki-version.h` file says ```c
#define CONTIKI_VERSION_STRING "Contiki 3.x"
```

**Comment by mithro** [comment]
I've moved these directories around in the nextgen to make this clearer. https://github.com/timvideos/HDMI2USB-misoc-firmware/commit/8017ff809fe6ca692d140956ffc59acb1a041d9d

third_party/libuip contains the TCP/UDP/IP stack from contiki
firmware/uip - Contains the "driver" part, which connects the uip stack to liteeth.

Still need to figure out where exactly / what version of uip is in third_party/uip.

**Comment by enjoy-digital** [comment]
Closing, now tracked in: https://github.com/timvideos/HDMI2USB-litex-firmware
