### ISSUE TITLE
Figure out if we are always booting from flash?

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#8]
We use to use an embedded ROM for the lm32 firmware.

Now with the liteDRAM fix, we can use the lm32 from SPI flash.

It was handy to have the lm32 firmware in the ROM as it allowed just loading the gateware and have the thing boot into operating state. The increase build time is probably not worth the simplicity though?

The BIOS is still embedded in the gateware, which still makes sense as it means you can load the gateware and then load from something like the UART or Ethernet without modifying the SPI flash.

I think the boot order should probably be;
 1a) SPI Flash
 1b) ROM boot (if still supported)
 2) netboot
 3) serialboot

**Comment by enjoy-digital** [comment]
Not sure we are going to support having the cpu firmware in ROM since this uses too much block rams, which means difficults P&R: long, random  and not meeting timings.
We will simply have the firmware in flash or loaded with netboot or serialboot.
